terminate called after throwing an instance of 'boost::wrapexcept<std::overflow_error>'
  what():  Error in function boost::math::erfc_inv<long double>(long double, long double): Overflow Error
==690114==  If you believe this happened as a result of a stack
==690114==  overflow in your program's main thread (unlikely but
==690114==  possible), you can try to increase the size of the
==690114==  main thread stack using the --main-stacksize= flag.
==690114==  The main thread stack size used in this run was 8388608.
Segmentation fault (core dumped)
